# configuration file for variables used in the program

imageSizeY: 640
imageSizeX: 640
averageSizeOfFish: 70
randomizeFish: 1

dataDirectory: 'data'

#shouldAddPatchyNoise: False
#shouldAddStaticNoise: False
# Small values for debugging purposes
amountOfData: 5
fractionForTraining: 1

